# Generated by Django 6.0.4 on 2026-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
