# Generated by Django 6.0.4 on 2026-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankmodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='transaction_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
